# Use a common base to keep things consistent
FROM node:22-alpine AS base

# ==========================================
# STAGE 1: Install Dependencies
# ==========================================
FROM base AS deps
# Alpine sometimes needs this package for Node to run perfectly
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files and install ALL dependencies (including dev)
COPY package.json package-lock.json* ./
RUN npm ci

# ==========================================
# STAGE 2: Build the App
# ==========================================
FROM base AS builder
WORKDIR /app

# Copy the node_modules from the 'deps' stage
COPY --from=deps /app/node_modules /app/node_modules
# Copy all your source code
COPY . /app

# Disable Next.js telemetry during build (optional but recommended)
ENV NEXT_TELEMETRY_DISABLED 1

# Build the Next.js app
RUN npm run build

# ==========================================
# STAGE 3: Production Server (The final image)
# ==========================================
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Security Best Practice: Run the app as a non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the public folder (static assets like images)
COPY --from=builder /app/public ./public

# Copy the standalone output folder generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy the static build files
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY version.txt /app/version.txt

# Switch to the non-root user
USER nextjs

EXPOSE 3000
ENV PORT 3000
# Needed for standalone mode to listen on all network interfaces
ENV HOSTNAME "0.0.0.0" 

# Note: Standalone mode generates a custom server.js, so we run that directly
# instead of using 'npm start'
CMD ["node", "server.js"]
