---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-svc
  labels:
    app: {{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}-{{ .Release.Namespace }}
