import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BottomNav } from "@/components/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased bg-zinc-950 overflow-hidden">
        {/* Main Viewport Wrapper */}
        <div className="h-screen w-screen flex justify-center relative">
          
          {/* Main Interface Shell (1000px wide) */}
          <div className="relative h-full w-full max-w-[1000px] bg-zinc-900 shadow-2xl border-x border-zinc-800 flex flex-col">
            
            {/* This is where your page content (Search + Cards) will inject */}
            {children}

            {/* Persistent Navbar pinned to the bottom of the shell */}
            <BottomNav />
          </div>

        </div>
      </body>
    </html>
  );
}